### PR TITLE
Make Adafruit_MP3 usable in CircuitPython, too

### PR DESCRIPTION
**Pull request by jepler**
I am working on adding MP3 playback to CircuitPython using Adafruit_MP3 as the base implementation of MP3 decoding.  My work in progress code successfully plays back MP3s,
but these changes are required in Adafruit_MP3.

I also verified that the modified Adafruit_MP3 still works in the Arduino environment, by building and running the `play_from_header` example on a pyportal m4.  No functional changes on Arduino are intended, including the way it uses static allocation for the mp3 decoder's storage.

### CODE REVIEW

**Comment by jepler** [comment]
@ladyada looks like I can't request a review in this repository, but I bet you're motivated to take a look at this :)

**Comment by ladyada** [comment]
thanks! yes i will test this on a metro m4 + my audio playback shield :)

**Comment by ladyada** [comment]
tested!

**Comment by ladyada** [comment]
i could add you as an 'arduino library' collaborator but its a noisy group! just tag me :)

**Pull request merged**
