### PR TITLE
- Fixed issues with Teensy support - The code `NVIC_DisableIRQ(MP3_IR…

### PR DESCRIPTION
**Pull request by richteel**
- Fixed issues with Teensy support - The code NVIC_DisableIRQ(MP3_IRQn); applies only to the feather and metro m4 but was applied to all boards which resulted in MP3_IRQn being undefined. (Adafruit_MP3.cpp)
- Added support for Teensy 3.5 - Added defined(__MK64FX512__) wherever defined(__MK66FX1M0__) was found
- Added/modified comments on compiler directives for Teensy boards
- Included test.mp3 sample file (58.3 KB)
- Fix applied to library and the "playfromSD.ino" example only. (Other examples may have the same errors so use the above notes to fix other examples if needed.)

NOTE: This release was tested with the Teensy 3.5 only. It is expected that it will work with all other supported boards. (At least as supported as the previous version.)

### CODE REVIEW

**Comment by kesterlester** [comment]
Is there anything I/we/others can do to get this request merged and into a new release of the Adafruit_MP3 library? I have just been pointed to it as a fix for Teensy 3.6 problems I was having over on https://github.com/adafruit/Adafruit_MP3/issues/7.  The merge request seems to have been hanging around for a year now.  I am not in a position to say whether this is a COMPLETE fix for everything needed to get this MP3 library working on the Teensy 3 series, however it is certainly better than the current latest release 1.0.4, in that I can at least now compile and can commence hardware testing .... :)

**Review by kesterlester — APPROVED** [review]
I found these changes useful. They allowed me to compile for and upload code to Teensy 3.6, where it subsequently ran -- which previously I was unable to do with the stock 1.0.4 release.   I should add that I am not yet in a position to declare that actual MP3s are decoded successfully - as I have no audio hardware connected to my Teensy 3.6, yet.  However, I have no reason to believe it is NOT working.

**Comment by ladyada** [comment]
hiya we had to fix the branch, it had merge conflicts. please try the latest branch in this PR (see command line instructions) and let us know if it still works!

**Comment by kesterlester** [comment]
Am checking here I am not misinterpreting your request.   What I've done on my local machine is the following ...

```
git clone https://github.com/adafruit/Adafruit_MP3.git
cd Adafruit_MP3/
git checkout -b MOO     # Without this next line is unhappy!
git fetch origin pull/3/head:master
git checkout master      # Going back to master to see what I am here to see ....
```

The last command tells me ...

```
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
```

... which I believe means that I now have a master that includes both the merged changes from richteel and the conflict-resolution fixes from you from the last hour or two.  A quick check of a few lines of src/Adafruit_MP3.cpp seems to confirm this.

I note that the resulting code is a lot more white-space-messy than it was prior to this merge.  I suspect someone did a whitespace cleanup on master recently, that this merge has “undone” all that good work.  I don’t know how much the project cares about whitespace.

Nonetheless, whitespace changes aside:

- I can confirm that I can use the Adafruit_MP3 library as checked out above, to the extent that
- I can compile the supplied “play_from_SD” example,
- I can upload that code to a Teensy 3.6, and see sensible output from the serial monitor.

As before I cannot confirm that MP3s actually decode and play as I have no suitable hardware to check this at present.

**Comment by ladyada** [comment]
image

**Comment by kesterlester** [comment]
I can't see those instructions as I don't have write access (supposedly). Here is what I see:
image

**Comment by ladyada** [comment]
type the words in the screenshot

**Comment by kesterlester** [comment]
In summary, same results as before after following the Step 1 instructions from your screenshot

- Teensy 3.6 examples compile.
- Teensy 3.6 examples upload to hardware.
- Serial monitor shows sensible looking output.
- [Update added two days after original post] : MP3 decoding is now tested and is also seen to work well on a Teensy 3.6. That's a good exercise of the whole chain. :)

This was doing:

```
git clone https://github.com/adafruit/Adafruit_MP3.git
cd Adafruit_MP3
git checkout -b richteel-master master
git pull https://github.com/richteel/Adafruit_MP3.git master
```
It was reassuring to see that the above commands ultimately given me the same checked-out source (bit for bit) I tested in my last post -- though by a more efficient route, and leaving the rep in a happier state.

**Pull request merged**
